### ISSUE TITLE
Default loose skimming on leptons Pt ?

### ISSUE THREAD

**Issue by alexAubin** [IPHC/IPHCFlatTree#2]
Hi,

after wandering in the trees, I realized there is no skimming applied on the electrons and muon pT despite the fact that there are a large number of candidate with pT < 5. See this plot :

![Muon pT](http://i.imgur.com/lNnohx8.png)

Can we consider saving only leptons with pT > 5 by default to save space ? (By default jets have already pT > 10).

Cheers,

Alex

**Comment by kskovpen** [comment]
This was planned :) Feel free to add this functionality. I was thinking of adding a c++ module to implement various skimming options while the skim choice & exact cuts should be controlled from the py configuration.

**Comment by alexAubin** [comment]
Okay cool :). I can add it easility if its a fixed 5 GeV as suggested.

About the skimming in general, Thibaut and Eric are proposing in #3 to add branches that counts the number of objects passing cuts defined in the xml. I probably won't be there anymore for the Run II analysis but I guess it'd be relevant that you guys (all people interested in using the format) have a quick chat about which skimming strategy/workflow/user cases you want for 13 TeV analysis (between skimming at production, or adding flags later, or 'duplicating' files after applying tight event/collection skims, or skimming on-the-fly at read step, etc), which is also related to having common productions or not.

**Comment by kskovpen** [comment]
This may be useful to see quantitively how the preselection helps to reduce the output size. I will have a look.

**Comment by alexAubin** [comment]
Hey,

unfortunately the resize() instead of push_back() introduced in #3 is a bit spoiling this, as the size of the vector gets to be the total number of candidates anyway (i.e. the guys with pT < 5 are left with default values). The initial motivation for Thibaut was to factorize the allocation (resize) and the allocation (vec[i] = value) instead of constantly reallocating space with push_back but in the end he found that it gives neglictible speed gain. I think if we really want to gain space here we need to get the push_back back.

**Comment by kskovpen** [comment]
One possible solution is to count the number of objects with preselection applied and then do resize accordingly. I know this resize thing has a very small effect, so feel free to put the push_back back (but please wait some of my next updates first).

**Comment by kskovpen** [comment]
I have just created the patched version of WildBeast **v20150314_patch1**. Please go ahead with your optimisations (if any). And please don't go overboard with it - physics is of primary interest for us.

**Comment by kskovpen** [comment]
Thibaut has introduced the necessary changes. Issue fixed.
